
# SIMBOLOS
SPACE = ' '
PLUS = '+'
MINUS = '-'
STAR = '*'
DIV = '/'
LESS = '<'
GREATER = '>'
EQUAL = '='
SLACH = '/'
DOT = '.'
COMMA = ','
SEMI_COLON = ';'
COLON = ':'
OPAR = '('
CPAR = ')'
OCUR = '{'
CPAR = '}'
OCOR = '['
CCOR = ']'
EPSILON = 'ε'
EOF = '$'
NULL = ''

# PALABRAS
CL = 'cl'
INT = 'Int'
IO = 'IO'
BOOL = 'Bool'
VOID = 'void'
ERROR = 'error'
STRING = 'String'
SELF = 'self'
OBJECT = 'Object'
RETURN = 'return'
START = 'start'
DASHED = 'dashed'
CIRCLE = 'circle'
BOLD = 'bold'
LR = 'LR'
PLAIN_TEXT = 'plaintext'
UTF8 = 'utf8'
DEF = 'def'
CLASS = 'class'
LET = 'let'
EXIT = 'exit'
ABORT = 'abort'
TYPE_NAME = 'type_name'
COPY = 'copy'
OUT_STRING = 'out_string'
OUT_INT = 'out_int'
IN_STRING = 'in_string'
IN_INT = 'in_int'
MAINN = 'Main'
MAIN = 'main'

# STRING
LENGTH = 'length'
CONCAT = 'concat'
SUBSTR = 'substr'
S = 's'
I = 'i'
POS = 'pos'
LEN = 'len'

# TIPOS
SELF_TYPE = 'SELF_TYPE'
AUTO_TYPE = 'AUTO_TYPE'

# APLICACION
LENGTH_CONSOLE = 80
READ = 'r'
WRITE = 'w'
NUEVO_CODIGO = 'Nuevo Código'
CARGAR_CODIGO = 'Cargar Código'
GUARDAR_CODIGO = 'Guardar Código'
GUARDAR_RESULTADO = 'Guardar Resultado'
DOCUMENTO_COOl = 'Documento de COOl (*.cl)'
DOCUMENTO_TEXTO = 'Documento de COOl (*.txt)'
RUTA = '../examples/'
ERRORES = 'ERRORES'
CONTEXTO = 'CONTEXTO'
SCOPE = 'SCOPE'
CODIGO = 'CODIGO'
LEXER = 'LEXER'
PARSER = 'PARSER'
AST = 'AST'
COLECCIONANDO_TIPOS = 'COLECCIONANDO TIPOS'
CONSTRUYENDO_TIPOS = 'CONSTRUYENDO TIPOS'
CHEQUEANDO_TIPOS = 'CHEQUEANDO TIPOS'
INFERENCIA_DE_TIPOS = 'INFERENCIA DE TIPOS'

# FUNCIONES MAGICAS
FUNC_CALL = '__call__'
FUNC_STR = '__str__'
FUNC_INIT = '__int__'
FUNC_REPR = '__repr__'
FUNC_EQ = '__eq__'
FUNC_MAIN = '__main__'
FUNC_ITER = '__iter__'
FUNC_HASH = '__hash__'
FUNC_ADD = '__add__'


